package com.animusmachinae.dll17.core.math

// GENERATED FILE - DO NOT EDIT BY HAND.
//
// Generator ID:      LOOKUP_GENERATOR_V1
// Generator version: 1
// Generator source:  tools/generate_lookup_tables.py
//
// Regenerate with:   python3 tools/generate_lookup_tables.py
// Verify with:       python3 tools/generate_lookup_tables.py --check
//
// Each table is bound to the digest of its canonical serialization. An edit
// here that is not reproduced by the generator fails LookupTable.verify().

/** Lookup tables generated by [GENERATOR_ID]. See DeterminismContractV1 section 11. */
public object GeneratedLookupTables {

    public const val GENERATOR_ID: String = "LOOKUP_GENERATOR_V1"
    public const val GENERATOR_VERSION: Int = 1

    /**
     * Fixed-point ramp from 0.000000 to 1.000000 across 256 equal intervals,
     * 257 entries inclusive of both endpoints.
     *
     * Mechanism proof only: R001 defines no table with organism meaning.
     *
     * Parameters: steps=256, scale=1_000_000, rounding=ROUND_HALF_AWAY_FROM_ZERO_V1
     * Entries: 257
     */
    public val UNIT_RAMP: LookupTable = LookupTable(
        tableId = "LOOKUP_UNIT_RAMP_V1",
        tableVersion = 1,
        expectedDigestHex = "5e8184bbc950ad382477edd4af3f2490ad71dc0fce92e29486865cddea81bcdb",
        values = longArrayOf(
            0L, 3906L, 7813L, 11719L, 15625L, 19531L, 23438L, 27344L,
            31250L, 35156L, 39063L, 42969L, 46875L, 50781L, 54688L, 58594L,
            62500L, 66406L, 70313L, 74219L, 78125L, 82031L, 85938L, 89844L,
            93750L, 97656L, 101563L, 105469L, 109375L, 113281L, 117188L, 121094L,
            125000L, 128906L, 132813L, 136719L, 140625L, 144531L, 148438L, 152344L,
            156250L, 160156L, 164063L, 167969L, 171875L, 175781L, 179688L, 183594L,
            187500L, 191406L, 195313L, 199219L, 203125L, 207031L, 210938L, 214844L,
            218750L, 222656L, 226563L, 230469L, 234375L, 238281L, 242188L, 246094L,
            250000L, 253906L, 257813L, 261719L, 265625L, 269531L, 273438L, 277344L,
            281250L, 285156L, 289063L, 292969L, 296875L, 300781L, 304688L, 308594L,
            312500L, 316406L, 320313L, 324219L, 328125L, 332031L, 335938L, 339844L,
            343750L, 347656L, 351563L, 355469L, 359375L, 363281L, 367188L, 371094L,
            375000L, 378906L, 382813L, 386719L, 390625L, 394531L, 398438L, 402344L,
            406250L, 410156L, 414063L, 417969L, 421875L, 425781L, 429688L, 433594L,
            437500L, 441406L, 445313L, 449219L, 453125L, 457031L, 460938L, 464844L,
            468750L, 472656L, 476563L, 480469L, 484375L, 488281L, 492188L, 496094L,
            500000L, 503906L, 507813L, 511719L, 515625L, 519531L, 523438L, 527344L,
            531250L, 535156L, 539063L, 542969L, 546875L, 550781L, 554688L, 558594L,
            562500L, 566406L, 570313L, 574219L, 578125L, 582031L, 585938L, 589844L,
            593750L, 597656L, 601563L, 605469L, 609375L, 613281L, 617188L, 621094L,
            625000L, 628906L, 632813L, 636719L, 640625L, 644531L, 648438L, 652344L,
            656250L, 660156L, 664063L, 667969L, 671875L, 675781L, 679688L, 683594L,
            687500L, 691406L, 695313L, 699219L, 703125L, 707031L, 710938L, 714844L,
            718750L, 722656L, 726563L, 730469L, 734375L, 738281L, 742188L, 746094L,
            750000L, 753906L, 757813L, 761719L, 765625L, 769531L, 773438L, 777344L,
            781250L, 785156L, 789063L, 792969L, 796875L, 800781L, 804688L, 808594L,
            812500L, 816406L, 820313L, 824219L, 828125L, 832031L, 835938L, 839844L,
            843750L, 847656L, 851563L, 855469L, 859375L, 863281L, 867188L, 871094L,
            875000L, 878906L, 882813L, 886719L, 890625L, 894531L, 898438L, 902344L,
            906250L, 910156L, 914063L, 917969L, 921875L, 925781L, 929688L, 933594L,
            937500L, 941406L, 945313L, 949219L, 953125L, 957031L, 960938L, 964844L,
            968750L, 972656L, 976563L, 980469L, 984375L, 988281L, 992188L, 996094L,
            1000000L,
        ),
    )

    /** Every generated table, for the unconditional verification sweep. */
    public val ALL: List<LookupTable> = listOf(
        UNIT_RAMP,
    )
}
